FROM nginxinc/nginx-unprivileged:stable-alpine
RUN apk add python3 python3-dev py3-pip build-base libressl-dev musl-dev libffi-dev rust cargo
RUN pip3 install pip --upgrade
RUN pip3 install certbot-nginx

ENV TACTICAL_DIR /opt/tactical

USER root

RUN deluser --remove-home nginx \
  && addgroup -S nginx -g 1000 \
  && adduser -S -G nginx -u 1000 nginx

RUN apk add --no-cache openssl bash

RUN chown -R nginx:nginx /etc/nginx

SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]

COPY docker/containers/tactical-nginx/entrypoint.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/entrypoint.sh

USER nginx

EXPOSE 4443 8080
