FROM nginxinc/nginx-unprivileged:stable-alpine
USER root

ENV TACTICAL_DIR /opt/tactical

RUN deluser --remove-home nginx \
  && addgroup -S nginx -g 1000 \
  && adduser -S -G nginx -u 1000 nginx

RUN apk add --no-cache openssl bash
RUN chown -R nginx:nginx /etc/nginx

RUN mkdir -p /opt/tactical/certs/
RUN chown -R nginx:nginx /opt/tactical/certs/
RUN curl https://get.acme.sh > /opt/tactical/certs/acme.sh

SHELL ["/bin/bash", "-e", "-o", "pipefail", "-c"]

COPY docker/containers/tactical-nginx/entrypoint.sh /docker-entrypoint.d/
RUN chmod +x /docker-entrypoint.d/entrypoint.sh

USER nginx

EXPOSE 4443 8080
